spring:
  application:
    name: salas-service
  datasource:
    url: jdbc:postgresql://db-salas:5432/salas_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      function:
        definition: reservaEventConsumer
      bindings:
        reservaEventConsumer-in-0:
          destination: reserva.eventos
      rabbit:
        bindings:
          reservaEventConsumer-in-0:
            consumer:
              binding-routing-key: reserva.#

server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ 