services:
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - rabbitmq
    networks:
      - net-gateway

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - JAVA_OPTS=-Xmx512m
    networks:
      - net-gateway

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - net-gateway

  usuario-service:
    build: ./usuario-service/usuario-service
    container_name: usuario-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://usuarios-db:5432/usuarios_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - usuarios-db
      - eureka-server
      - rabbitmq
    networks:
      - net-usuario
      - net-gateway

  salas-service:
    build: ./salas-service/salas-service
    container_name: salas-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://salas-db:5432/salas_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - salas-db
      - eureka-server
      - rabbitmq
    networks:
      - net-sala
      - net-gateway

  reserva-service:
    build: ./reserva-service/reserva-service
    container_name: reserva-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://reservas-db:5432/reservas_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - reservas-db
      - eureka-server
      - rabbitmq
    networks:
      - net-reserva
      - net-gateway

  usuarios-db:
    image: postgres:15-alpine
    container_name: usuarios-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: usuarios_db
    ports:
      - "5433:5432"
    networks:
      - net-usuario

  salas-db:
    image: postgres:15-alpine
    container_name: salas-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: salas_db
    ports:
      - "5434:5432"
    networks:
      - net-sala

  reservas-db:
    image: postgres:15-alpine
    container_name: reservas-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: reservas_db
    ports:
      - "5435:5432"
    networks:
      - net-reserva

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    ports:
      - "8084:8080"
    networks:
      - net-usuario
      - net-sala
      - net-reserva

networks:
  net-usuario:
  net-sala:
  net-reserva:
  net-gateway:
