server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: salas-service
          uri: lb://salas-service
          predicates:
            - Path=/api/rooms/**
          filters:
            - StripPrefix=1

        - id: reserva-service
          uri: lb://reserva-service
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=1

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/ 